In [1]:
# from astropy.io import fits
# from astropy.table import Table
# import numpy as np
# import matplotlib.pylab as plt 
# import matplotlib.lines as mlines
# from matplotlib.legend import Legend
# # from pythonds.basic.stack import Stack
# from math import *
import random
# from sklearn.neighbors import KDTree
# # from cosmoCalc import cosmoCalcfunc
# from findRadius import *
# from astropy import units as u
# from astropy.coordinates import FK5
# from astropy.coordinates import SkyCoord
# from astropy_healpix import HEALPix

from astropy.io import fits
from astropy.table import Table
import numpy as np
import matplotlib.pylab as plt 
import matplotlib.lines as mlines
from matplotlib.legend import Legend
from pythonds.basic.stack import Stack
from math import *
from sklearn.neighbors import KDTree
from lrg_plot_functions import *
from lrg_sum_functions import *
from cosmo_Calc import *
from divideByTwo import *
from readData import *
from nearNeighbors import *
from localBKG import *
from scipy import stats
from bestBkg import *
from astropy import stats
import healpy as hp

In [2]:
# Define all relevant physical variables needed throughout the program, including:
# - number of LRG sources
# - number of survey (non-LRG) sources
# - coordinates for LRGs
# - coordinates for survey sources
# - projected radius from LRGs
# - LRG redshift
# - gmag and rmag for survey sources
# - gmag and rmag for LRGs
# - (g-r) color survey sources
# - (g-r) color for LRGs

# Number of LRG sources
lrg = 25

# Number of survey (non-LRG) sources
survey = 500

# Fake coordinates for LRG sources
random.seed(1)
x0 = [np.random.uniform(0,5) for j in range(lrg)]

random.seed(2)
y0 = [np.random.uniform(0,5) for j in range(lrg)]

# y0 = random.sample(y0, len(y0))
print("length of fake LRG sources (ra) = ", len(x0))
print("length of fake LRG sources (dec) = ", len(y0))
# print("x0 = ", x0)
# print("y0 = ", y0)
# print(type(y0))

# Fake coordinates for survey sources
random.seed(3)
x1 = [np.random.uniform(0,5) for j in range(survey)]

random.seed(4)
y1 = [np.random.uniform(0,5) for j in range(survey)]
# y1 = random.sample(y1, len(y1))
    
print("length of fake survey sources (ra) = ", len(x1))
print("length of fake survey sources (dec) = ", len(y1))    

# In order for there to be at least one guaranteed satellite, combine the survey and lrg position arrays so that one
# survey source position is the same as an LRG position
x_plus = np.concatenate([x0, x1])
y_plus = np.concatenate([y0, y1])

# print("length of x_plus (ra) (lrgs + survey) =", len(x_plus))
# print("length of y_plus (dec) (lrg + survey) =", len(y_plus))

# Redshift for LRG 
random.seed(0.2)
z = [np.random.uniform(0.1,0.5) for j in range(lrg)]
    
print("length of array of redshifts for fake LRGs =", len(z))
print("max z = ", np.amax(z))
print("min z = ", np.amin(z))

# Magnitudes for survey sources
random.seed(15)
gmag_plus = [np.random.uniform(14,29) for j in range(len(x_plus))]
random.seed(16)
rmag_plus = [np.random.uniform(13,24) for j in range(len(x_plus))]

gmag_plus = np.array(gmag_plus)
rmag_plus = np.array(rmag_plus)
color_plus = gmag_plus - rmag_plus
    
# print("length of gmag for survey soruces =", len(gmag_plus))
# print("length of rmag for survey soruces =", len(rmag_plus))
# print("max gmag_plus = ", np.amax(gmag_plus))
# print("min gmag_plus = ", np.amin(gmag_plus))
# print("max rmag_plus = ", np.amax(rmag_plus))
# print("min rmag_plus = ", np.amin(rmag_plus))
# print("length of color_plus = ", len(color_plus))
# print("max color = ", np.amax(color_plus))
# print("min color = ", np.amin(color_plus))

random.seed(15)
gmag_survey = [np.random.uniform(14,29) for j in range(len(x1))]
random.seed(16)
rmag_survey = [np.random.uniform(13,24) for j in range(len(x1))]

gmag_survey = np.array(gmag_survey)
rmag_survey = np.array(rmag_survey)
color_survey = gmag_survey - rmag_survey
    
print("length of gmag for survey soruces =", len(gmag_survey))
print("length of rmag for survey soruces =", len(rmag_survey))
print("max gmag_plus = ", np.amax(gmag_survey))
print("min gmag_plus = ", np.amin(gmag_survey))
print("max rmag_plus = ", np.amax(rmag_survey))
print("min rmag_plus = ", np.amin(rmag_survey))
print("length of color_plus = ", len(color_survey))
print("max color = ", np.amax(color_survey))
print("min color = ", np.amin(color_survey))

# Magnitudes for LRG sources
random.seed(20)
gmag_lrg = [np.random.uniform(17,23) for j in range(lrg)]
random.seed(21)
rmag_lrg = [np.random.uniform(16,21) for j in range(lrg)]
    
print("length of gmag for survey soruces =", len(gmag_lrg))
print("length of rmag for survey soruces =", len(rmag_lrg))
print("max gmag_lrg = ", np.amax(gmag_lrg))
print("min gmag_lrg = ", np.amin(gmag_lrg))
print("max rmag_lrg = ", np.amax(rmag_lrg))
print("min rmag_lrg = ", np.amin(rmag_lrg))

gmag_lrg = np.array(gmag_lrg)
rmag_lrg = np.array(rmag_lrg)
color_lrg = gmag_lrg - rmag_lrg
print("length of color_lrg = ", len(color_lrg))

distance = 0.5 # in Mpc
print("distance in Mpc =", distance)
distance_kpc = distance * 10.**3. # in kpc
print("distance in kpc = ", distance_kpc)

length of fake LRG sources (ra) =  25
length of fake LRG sources (dec) =  25
length of fake survey sources (ra) =  500
length of fake survey sources (dec) =  500
length of array of redshifts for fake LRGs = 25
max z =  0.4713696179866542
min z =  0.10966222225423464
length of gmag for survey soruces = 500
length of rmag for survey soruces = 500
max gmag_plus =  28.97049103200424
min gmag_plus =  14.013798477535843
max rmag_plus =  23.956829266764597
min rmag_plus =  13.041176866450268
length of color_plus =  500
max color =  15.169471564693211
min color =  -9.597468690196166
length of gmag for survey soruces = 25
length of rmag for survey soruces = 25
max gmag_lrg =  22.919883476187206
min gmag_lrg =  17.749993057247647
max rmag_lrg =  20.878120544426235
min rmag_lrg =  16.023020636926045
length of color_lrg =  25
distance in Mpc = 0.5
distance in kpc =  500.0


In [3]:
# cosmoCalc function to find comoving radial distance (DCMR_Mpc) and scale (kpc_DA)

def cosmoCalc(z):

# 	import numpy as np
# 	from math import sqrt
# 	from math import exp
# 	from math import sin
# 	from math import pi

# Calculate scale to get areas
	H0 = 69.6
	WM = 0.286
	WV = 0.714
# z = 0.209855

# initialize constants

	WR = 0.        # Omega(radiation)
	WK = 0.        # Omega curvaturve = 1-Omega(total)
	c = 299792.458 # velocity of light in km/sec
	Tyr = 977.8    # coefficent for converting 1/H into Gyr
	DTT = 0.5      # time from z to now in units of 1/H0
	DTT_Gyr = []  # value of DTT in Gyr
	age = 0.5      # age of Universe in units of 1/H0
	age_Gyr = []  # value of age in Gyr
	zage = 0.1     # age of Universe at redshift z in units of 1/H0
	zage_Gyr = [] # value of zage in Gyr
	DCMR = 0.0     # comoving radial distance in units of c/H0
	DCMR_Mpc = [] 
	DCMR_Gyr = []
	DA = 0.0       # angular size distance
	DA_Mpc = []
	DA_Gyr = []
	kpc_DA = []
	DL = 0.0       # luminosity distance
	DL_Mpc = []
	DL_Gyr = []   # DL in units of billions of light years
	V_Gpc = []
	a = 1.0        # 1/(1+z), the scale factor of the Universe
	az = 0.5       # 1/(1+z(object))

	h = H0/100.
	WR = 4.165E-5/(h*h)   # includes 3 massless neutrino species, T0 = 2.72528
	WK = 1.-WM-WR-WV

	for j in range(len(z)):
		az = 1.0/(1+1.0*z[j])
		age = 0.
		n=1000         # number of points in integrals
		for i in range(n):
			a = az*(i+0.5)/n
			adot = sqrt(WK+(WM/a)+(WR/(a*a))+(WV*a*a))
			age = age + 1./adot

		zage = az*age/n
		zage_Gyr.append((Tyr/H0)*zage)
		DTT = 0.0
		DCMR = 0.0

	# do integral over a=1/(1+z) from az to 1 in n steps, midpoint rule
		for i in range(n):
			a = az+(1.-az)*(i+0.5)/n
			adot = sqrt(WK+(WM/a)+(WR/(a*a))+(WV*a*a))
			DTT = DTT + 1./adot
			DCMR = DCMR + 1./(a*adot)

		DTT = (1.-az)*DTT/n
		DCMR = (1.-az)*DCMR/n
		age = DTT+zage
		age_Gyr.append(age*(Tyr/H0))
		DTT_Gyr.append((Tyr/H0)*DTT)
		DCMR_Gyr.append((Tyr/H0)*DCMR)
		DCMR_Mpc.append((c/H0)*DCMR)

	# tangential comoving distance

		ratio = 1.00
		x = sqrt(abs(WK))*DCMR
		if x > 0.1:
			if WK > 0:
				ratio =  0.5*(exp(x)-exp(-x))/x 
			else:
				ratio = sin(x)/x
		else:
			y = x*x
		if WK < 0: y = -y
		ratio = 1. + y/6. + y*y/120.
		DCMT = ratio*DCMR
		DA = az*DCMT
		DA_Mpc.append((c/H0)*DA)
		kpc_DA.append(DA_Mpc[j]/206.264806)
		DA_Gyr.append((Tyr/H0)*DA)
		DL = DA/(az*az)
		DL_Mpc.append((c/H0)*DL)
		DL_Gyr.append((Tyr/H0)*DL)

	# comoving volume computation

		ratio = 1.00
		x = sqrt(abs(WK))*DCMR
		if x > 0.1:
			if WK > 0:
				ratio = (0.125*(exp(2.*x)-exp(-2.*x))-x/2.)/(x*x*x/3.)
			else:
				ratio = (x/2. - sin(2.*x)/4.)/(x*x*x/3.)
		else:
			y = x*x
			if WK < 0: y = -y
			ratio = 1. + y/5. + (2./105.)*y*y
		VCM = ratio*DCMR*DCMR*DCMR/3.
		V_Gpc.append(4.*pi*((0.001*c/H0)**3)*VCM)

	return(age_Gyr, zage_Gyr, DTT_Gyr, DL_Mpc, DL_Gyr, V_Gpc, DA_Mpc, DA_Gyr, DCMR_Mpc, DCMR_Gyr, kpc_DA, DL_Mpc, DL_Gyr)


age_Gyr, zage_Gyr, DTT_Gyr, DL_Mpc, DL_Gyr, V_Gpc, DA_Mpc, DA_Gyr, DCMR_Mpc, DCMR_Gyr, kpc_DA, DL_Mpc, DL_Gyr = cosmoCalc(z)


In [4]:
# Calculate surface density as a function of color and magniude by making a 2D histogram and dividing by the area
# of the survey space

# Create a 2D histogram that creates evenly-spaced bins and counts the points in each bin
# H is the matrix with the number of points per bin
# xedges, yedges are the bounds of the bins
# H, xedges, yedges = np.histogram2d(x0, y0, bins=[5,5], normed=False)

# row = 5
# column = 5

xedges = np.array([13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])
yedges = np.array([-10., -8., -6., -4., -2., 0., 2., 4., 6., 8., 10., 12., 14., 16.]) 

# xedges =  [ 13.,  15.,  17.,   19.,  21., 24.]
# yedges =  [ -10.,  -5.,   0.,   5.,  11., 16.]

# creates histogram for survey sources; excluses LRGs
H, xedges, yedges = np.histogram2d(rmag_survey, color_survey, bins=(xedges,yedges), normed=False)
print("H:")
print(H)
print('-------')
print('shape H')
print(np.shape(H))

# Uses the numbers counted in the histogram to calculate a surface density: For each cell, the number of sources
# divided by the area 
sd = H/(25.) # * (3600.**2.)) # converts 25 square degrees to square arcseconds
print("sd:")
print(sd)
print('-------')

# Scatter plot of points with bin lines drawn
# fig, ax = plt.subplots()
# ax.set_xticks(xedges, minor=False)
# ax.set_yticks(yedges, minor=True)
# ax.xaxis.grid(True, which='major')
# ax.yaxis.grid(True, which='minor')

# plt.scatter(rmag_survey, color_survey, s = 4, color='red')
# plt.scatter(rmag_lrg, color_lrg, s = 4, color='blue')
# plt.gca().invert_xaxis()
# plt.title("Color-Magnitude Diagram")
# plt.show()

# # color codes bins by surface density with color bar; should make sense when compared to scatter plot
# plt.imshow(sd, cmap=plt.cm.PuRd, extent=(xedges[0], xedges[len(xedges)-1], yedges[0], yedges[len(yedges)-1]))
# plt.colorbar(orientation='vertical')
# plt.gca().invert_xaxis()
# plt.title("Surface Density Histogram")
# plt.show()

# # Playing with only plotting one bin at a time. Not useful now but I don't want to forget it.
# # dx = x[np.where((x>=xedges[1]) & (x<=xedges[2]) & (y>=yedges[1]) & (y<=yedges[2]))]
# # dy = y[np.where((x>=xedges[1]) & (x<=xedges[2]) & (y>=yedges[1]) & (y<=yedges[2]))]

# # plt.scatter(dx,dy)
# # plt.show()

# # print(H.shape)

# # print(sd[0,0])
# # print(sd[0,1])
# # print(sd[1,0])
# # print(sd[1,1])

# print("xedges = ", xedges)
# print("yedges = ", yedges)

H:
[[ 0.  0.  0.  0.  0.  2.  7.  6.  5.  7.  6.  6.  2.]
 [ 0.  0.  0.  0.  2.  7.  2.  6.  4.  6.  3.  8.  2.]
 [ 0.  0.  0.  0.  5. 11.  7.  3.  7.  5.  3.  2.  0.]
 [ 0.  0.  0.  0.  2.  3.  6.  5.  6.  7. 10.  2.  0.]
 [ 0.  0.  0.  3.  4.  8.  3. 10.  4.  6.  5.  0.  0.]
 [ 0.  0.  2.  8.  4.  6.  5.  9.  5.  9.  2.  0.  0.]
 [ 0.  0.  5.  4.  9.  6.  9.  7.  3.  2.  0.  0.  0.]
 [ 0.  0.  7.  7.  4.  4. 10.  7.  5.  4.  0.  0.  0.]
 [ 0.  9.  8.  8.  8.  3.  6.  6.  2.  0.  0.  0.  0.]
 [ 3.  7.  8.  7.  7.  5.  2.  7.  4.  0.  0.  0.  0.]
 [ 7.  4.  5. 11.  7.  8.  4.  3.  0.  0.  0.  0.  0.]]
-------
shape H
(11, 13)
sd:
[[0.   0.   0.   0.   0.   0.08 0.28 0.24 0.2  0.28 0.24 0.24 0.08]
 [0.   0.   0.   0.   0.08 0.28 0.08 0.24 0.16 0.24 0.12 0.32 0.08]
 [0.   0.   0.   0.   0.2  0.44 0.28 0.12 0.28 0.2  0.12 0.08 0.  ]
 [0.   0.   0.   0.   0.08 0.12 0.24 0.2  0.24 0.28 0.4  0.08 0.  ]
 [0.   0.   0.   0.12 0.16 0.32 0.12 0.4  0.16 0.24 0.2  0.   0.  ]
 [0.   0.   0.08 0.32 

In [5]:
distance = 0.5 # must be in Mpc

distance_kpc, near, gal_tree = nearNeighbor(distance, kpc_DA, x0, y0, x1, y1, rmag_lrg, rmag_survey, color_lrg, color_survey, xedges, yedges)

print('end nearNeighbor')

near = np.asarray(near)
print(near.shape)

end nearNeighbor
(25, 11, 13)


In [6]:
distance_r2 = 0.4 # in degree
distance_r3 = 0.5 # in degree

numbkg, med_local, sigma, omega, Nbkg = localBKG_and_interlopers(distance_kpc, distance_r2, distance_r3, kpc_DA, x0, y0, x1, y1, rmag_lrg, rmag_survey, color_lrg, color_survey, xedges, yedges)

print("end bkg")

len index_r3: 25
shape local_bkg:  (25, 11, 13)
type local_bkg:  <class 'numpy.ndarray'>
0
0.2827433388230813
[[0.         0.         0.         0.         0.         0.
  0.         3.53677651 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         3.53677651 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         3.53677651
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         3.53677651
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         3.53677651 0.
  0.      

In [ ]:
# Counting near neighbors using KDTree
# Result is an array of the number of near neighbors each LRG has

dist1 = []
for i in range(len(kpc_DA)):
#     dist.append((distance_kpc / kpc_DA[i]) * 1./3600.) 
    dist1.append((300. / kpc_DA[i]) * 1./3600.) 
    
dist2 = []
for i in range(len(kpc_DA)):
#     dist.append((distance_kpc / kpc_DA[i]) * 1./3600.) 
    dist2.append((700. / kpc_DA[i]) * 1./3600.) 

# print("len dist is", len(dist))
# print('len ra is', len(x0))
# print(type(x1))
# print(type(y1))
# print(type(x0))
# print(type(y0))

# Plots LRG sources and EDR sources
plt.scatter(x1, y1, s = 3, color='red')
plt.scatter(x0, y0, s = 3, color='blue')

# Draws circle of some radius around the LRG sources
# Circles too small to really see in the plot, but I have tested it with bigger radii to make sure it works if I
# ever need it.
circle = []
for i in range(len(x0)):
    circle1 = plt.Circle((x0[i],y0[i]), dist1[i], color='green', fill=False)
    circle2 = plt.Circle((x0[i],y0[i]), dist2[i], color='purple', fill=False)
    plt.gcf().gca().add_artist(circle1)
    plt.gcf().gca().add_artist(circle2)
    
# prints ID numbers next to LRG
# This will be slightly different when using real data because those sources have real ID numbers
a = np.arange(0,lrg)
for i, txt in enumerate(a):
    text = plt.annotate(txt, (x0[i],y0[i]))
    text.set_fontsize(12)

plt.rcParams["figure.figsize"] = [15, 15]
plt.show()

# Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
# zip_list0 = list(zip(x0, y0))
zip_list0 = list(zip(x0, y0)) # Fake LRG sources
x = np.concatenate([x0,x1])
y = np.concatenate([y0,y1])
zip_list1 = list(zip(x, y)) # Fake EDR sources
# print(type(zip_list))
# print(zip_list)
# print('type zip_list0[0]:',type(zip_list0[0]))
# print(zip_list0[0])
# print('len zip_list0:', len(zip_list0))

# Creates a tree of EDR sources
gal_tree = KDTree(zip_list1)

# returns a list of EDR sources that are within some radius r of an LRG
nn1 = gal_tree.query_radius(zip_list0,r=dist1,count_only=True)
# print(np.sum(nn1))
nn2 = gal_tree.query_radius(zip_list0,r=dist2,count_only=True)
# print(np.sum(nn2))
# print(np.sum(nn2) - np.sum(nn1))
# print("nn =", nn)
# print("length of nn = ", len(nn))

# find indices of near neighbors
ind = gal_tree.query_radius(zip_list0,r=dist2)
# print("length of nn index = ", len(ind))
# print("nn index = ", ind)

# ind = list(ind)
print(type(ind))
print(type(ind[0]))
ind2list = ind.tolist()
print(type(ind2list))
print(type(ind2list[0]))

index = []
for i in range(len(ind2list)):
    index.append(ind2list[i].tolist())

print(index)

# print(type(ind))
# print("index 0 =", ind[0])
# print("index 1 =", ind[1])
# print("index 2 =", ind[2])
# print("index 3 =", ind[3])
# print("index 4 =", ind[4])
# print("index 5 =", ind[5])
# print("index 6 =", ind[6])
# print("index 7 =", ind[7])
# print("index 8 =", ind[8])
# print("index 9 =", ind[9])

# print(type(ind[0]))
# print(type(ind))

total_ind = np.concatenate(ind)
# print("total index array: ", total_ind)
# print(len(total_ind))

# Array that gives actual number of near neighbors for every LRG
num = []

for i in range(len(ind)):
    num.append(len(ind[i]))
    
for i in range(len(index)):
    index[i] = [x for x in index[i] if x != i]
# #     print(ind[i])
#     if (i == any(index[i])):
#         print('match')
#     else:
#         print('no match')
    
print(index)
    
# print("num is", num)
# print('num0 is', num0)
# print("length of num is", len(num))

# print(type(ind))
# print(type(ind[0]))
# print(nn1)
# print(nn2)
# print(ind)

# print(nn1[1])
# print(nn2[1])
# print(ind[1]) # corresponds with outer radius in this code

In [ ]:
# Create 2D histograms in bins of color and magnitude for near neighbors found above
# Result is a 2D array of the number of near neighbors for every LRG in bins of color and magnitude.

near = []
rmag = np.concatenate([rmag_lrg, rmag_survey])
color = np.concatenate([color_lrg, color_survey])

# Creates one list of number of near neighbors for every LRG (number of lists = number of LRGs)
for i in range(len(index)):
    if len(index[i]) == 0:
        hist2d = np.zeros((len(xedges)-1,len(yedges)-1))
        near.append(hist2d)
#         print("list is empty")
#         print(near)
#         print(np.shape(hist2d))
    else:
#         print(ind[i])
#         print(i)
        hist2d, x_notuse, y_notuse = np.histogram2d(rmag[index[i]], color[index[i]], bins=(xedges, yedges), normed=False)
        near.append(hist2d)
#         print('list is not empty')
#         print(hist2d)
#         print(np.shape(hist2d))

print(np.shape(near))
# print(np.shape(hist2d))
# print(len(hist2d))
# # print(near)
# print(len(near))

sumnear = []
for i in range(len(near)):
    sumnear.append(np.sum(near[i]))
    
nearmean = np.mean(sumnear)
print(nearmean)

In [ ]:
# sum_sigma_kpc1, error_kpc1, dist_outer_kpc1, radius_inner_kpc1, bkg_kpc1, dist_outer1, radius_outer_kpc1 = findRadius(5., 5.5, kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)
# sum_sigma_kpc2, error_kpc2, dist_outer_kpc2, radius_inner_kpc2, bkg_kpc2, dist_outer2, radius_outer_kpc2 = findRadius(5.5, 6., kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)
# sum_sigma_kpc3, error_kpc3, dist_outer_kpc3, radius_inner_kpc3, bkg_kpc3, dist_outer3, radius_outer_kpc3 = findRadius(6., 6.5, kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)
# sum_sigma_kpc4, error_kpc4, dist_outer_kpc4, radius_inner_kpc4, bkg_kpc4, dist_outer4, radius_outer_kpc4 = findRadius(6.5, 7., kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)
# sum_sigma_kpc5, error_kpc5, dist_outer_kpc5, radius_inner_kpc5, bkg_kpc5, dist_outer5, radius_outer_kpc5 = findRadius(7., 7.5, kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)
# sum_sigma_kpc6, error_kpc6, dist_outer_kpc6, radius_inner_kpc6, bkg_kpc6, dist_outer6, radius_outer_kpc6 = findRadius(7.5, 8., kpc_DA, x0, y0, x1, y1, rmag_survey, color_survey, xedges, yedges)


# print(sum_sigma_kpc)
# print(len(dist_outer_kpc))
# print(np.sum(bkg_kpc))
# print(dist_outer.shape)

# sumSig = [sum_sigma_kpc1, sum_sigma_kpc2, sum_sigma_kpc3, sum_sigma_kpc4, sum_sigma_kpc5, sum_sigma_kpc6]
# radius_kpc = [radius_outer_kpc1, radius_outer_kpc2, radius_outer_kpc3, radius_outer_kpc4, radius_outer_kpc5, radius_outer_kpc6]

# plt.scatter(radius_kpc, sumSig)
# plt.show()


In [ ]:
#### TESTING FOR BESTBKG

# Convert inner radius from Mpc to kpc
# radius_inner = 5.  # in Mpc
# radius_inner_kpc = radius_inner * 10. ** 3.  # in kpc

# Converts inner radius from kpc to arcsec
# radius_inner_arcsec = []
# for i in range(len(kpc_DA)):
#     radius_inner_arcsec.append(radius_inner_kpc / kpc_DA[i]) # only using for bkg array so only need dist_inner in arcsec

# Convert outer radius from Mpc to kpc
# radius_outer = 10.  # in Mpc
# radius_outer_kpc = radius_outer * 10. ** 3.  # in kpc
radius_outer_kpc = 5000.

# Converts outer radius from kpc to degree
radius_outer_deg = []
for i in range(len(kpc_DA)):
    radius_outer_deg.append((radius_outer_kpc / kpc_DA[i]) * 1. / 3600.)

# Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
zip_list_LRG = list(zip(x0, y0))
zip_list_BKG = list(zip(x1, y1))

# Creates a tree of EDR sources
gal_tree_outer = KDTree(zip_list_BKG)

# find indices of sources
# creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
# arrays could be empty
ind_outer = gal_tree_outer.query_radius(zip_list_LRG, r=radius_outer_deg)

# returns a list of sources and their distances from the LRG within radius dist_outer
nn_outer, dist_outer = gal_tree_outer.query_radius(zip_list_LRG, r=radius_outer_deg, return_distance=True)

print(nn_outer[1])
print(dist_outer[1])
print(len(dist_outer))
print(ind_outer[1]) # omg nn_outer is the same thing as ind_outer!
print(type(nn_outer))

In [ ]:
dist_outer_arcsec = []
temp = []
for i in range(len(kpc_DA)):
    for j in range(len(dist_outer[i])):
        x = np.float64(dist_outer[i][j] / kpc_DA[i])
#         print(type(x))
        temp.append(x)
    dist_outer_arcsec.append(temp)
    temp = []
        
# print(len(dist_outer_arcsec))
# print(dist_outer_arcsec[49])
# print(type(dist_outer_arcsec))
# print(type(dist_outer_arcsec[0]))
# print(type(dist_outer_arcsec[0][0]))
# print(len(dist_outer_arcsec))
# print(dist_outer_arcsec.dtype)
# print(dist_outer_arcsec)
print('-------------')

# a = dist_outer[49]/kpc_DA[49]
# print(a)


dist_outer_kpc = []
temp2 = []
for i in range(len(kpc_DA)):
    for j in range(len(dist_outer[i])):
        y = np.float64(dist_outer[i][j] * 3600. * kpc_DA[i])
        temp2.append(y)
    dist_outer_kpc.append(temp2)
    temp2 = []
    
# print(len(dist_outer_kpc))
print(dist_outer_kpc[10])

# a = dist_outer[9] * 3600. * kpc_DA[9]
# print(a)


dist_outer_Mpc = []
temp3 = []
for i in range(len(dist_outer_kpc)):
    for j in range(len(dist_outer_kpc[i])):
        temp3.append(np.asarray(dist_outer_kpc[i]) / 1000.)
    dist_outer_Mpc.append([temp3])
    temp3 = []

# print(len(dist_outer_Mpc))
# print(dist_outer_Mpc[27])

# a = np.asarray(dist_outer_kpc[27]) * (1./1000.)
# print(a)

a = 10.
b = 5.
# inner_radius = (radius_outer_kpc/a)*b
inner_radius = 3000.
# print(inner_radius)
# outer_radius = (radius_outer_kpc/a)*(b + 1.)
outer_radius = 4000.
# print(outer_radius)


# print('-------------------')

# index = []
# for i in range(len(ind_outer)):
dist_index = np.where(np.asarray(dist_outer_kpc[10]) > 2000.)[0] # & (np.asarray(dist_outer_kpc[2]) < 6000.))[0]

print(dist_index)

# This is how I can make a new array that contains only relevant values
import numpy as np
values = np.array([1,2,3,1,2,4,5,6,3,2,1])
print(type(values))
print(type(values[1]))
searchval = 3
ii = np.where(values <= searchval)[0]
print(ii)


In [ ]:
def bestBKG(a, b, dist_outer, radius_outer_kpc, kpc_DA, xedges, yedges, rmag_survey, color_survey):
    
    # dist_outer is given in degree, since that is the input. This converts degree to arcsecond, kpc, and Mpc
    dist_outer_arcsec = []
    temp = []
    for i in range(len(kpc_DA)):
        for j in range(len(dist_outer[i])):
            temp.append(dist_outer[i][j] / kpc_DA[i])
        dist_outer_arcsec.append([temp])
        temp = []

    dist_outer_kpc = []
    temp2 = []
    for i in range(len(kpc_DA)):
        for j in range(len(dist_outer[i])):
            temp2.append(dist_outer[i][j] * 3600. * kpc_DA[i])
        dist_outer_kpc.append([temp2])
        temp2 = []
    
    dist_outer_Mpc = []
    temp3 = []
    for i in range(len(dist_outer_kpc)):
        for j in range(len(dist_outer_kpc[i])):
            temp3.append(np.asarray(dist_outer_kpc[i]) / 1000.)
        dist_outer_Mpc.append([temp3])
        temp3 = []

    
    inner_radius = (radius_outer_kpc/a)*b
    outer_radius = (radius_outer_kpc/a)*(b + 1.)
    
    # Creates CMDs of sources within the search radius for each LRG
    # Below is the loop for the physical radius
    bkg_kpc = []
    for i in range(len(ind_outer)):
        # Creates a zero array if there are no near neighbors
        if len(ind_outer[i][np.where((dist_outer_kpc[i] >= inner_radius) & (dist_outer_kpc[i] < outer_radius))] == 0):
            temp_kpc1 = np.zeros((len(xedges) - 1, len(yedges) - 1))
            bkg_kpc.append(temp_kpc1)
#             print("1")
        # Creates a 2D histogram for satellite galaxies
        else:
            temp_kpc2, x_notuse, y_notuse = np.histogram2d(
                rmag_survey[ind_outer[i][np.where((dist_outer_kpc[i] >= inner_radius) & (dist_outer_kpc[i] < outer_radius))]],
                color_survey[ind_outer[i][np.where((dist_outer_kpc[i] >= inner_radius) & (dist_outer_kpc[i] < outer_radius))]], bins=(xedges, yedges),
                normed=False)
            bkg_kpc.append(temp_kpc2)
#             print("2")
               
     # This area calculation only works for physical radius. Look at localBKG.py for how to get area in arcsec
    area_kpc = np.pi * ((outer_radius)**2. - (inner_radius)**2.)

    # Calculate the surface density sigma for each LRG
    sigma_kpc = []
    for i in range(len(bkg_kpc)):
        sigma_kpc.append(bkg_kpc[i] / area_kpc)

    # sigma_arcsec = []
    # for i in range(len(bkg_arcsec)):
    #     sigma_arcsec.append(bkg_arcsec[i] / area_annulus[i])

    sum_sigma_kpc = np.sum(sigma_kpc)
    # sum_sigma_arcsec = np.sum(sigma_arcsec)

#     error_kpc = np.sqrt(sum_sigma_kpc) / sum_sigma_kpc
    # error_arcsec = np.sqrt(sum_sigma_arcsec) / sum_sigma_arcsec

    return(sum_sigma_kpc, outer_radius, inner_radius, bkg_kpc) #, error_kpc)
 
               
sum_sigma_kpc, outer_radius, inner_radius, bkg_kpc = bestBKG(10., 5., dist_outer, radius_outer_kpc, kpc_DA, xedges, yedges, rmag_survey, color_survey)


In [ ]:
print(sum_sigma_kpc)
print(outer_radius)
print(inner_radius)
print(np.sum(bkg_kpc))
print(radius_outer_kpc)
print(inner_radius)
print(outer_radius)

In [ ]:
# Make CMDs for LRG near neighbors

# First, make one CMD for one set of near neighbors 

# Magnitudes for survey sources
# for i in range(1000):
#     gmag_survey = [random.uniform(1,100) for j in range(100)]
#     rmag_survey = [random.uniform(1,100) for j in range(100)]
    
# print("length gmag_survey = ", len(gmag_survey))
# print("length rmag_survey = ", len(rmag_survey))
# print("gmag_survey = ", gmag_survey[0])
# print("rmag_survey = ", rmag_survey[0])

# ra = x1
# dec = y1
# index = []
# print("length ind = ", len(ind))

# for i in range(len(ind)):
#     index = ind[i]
#     index_full = []
# #     print("index = ", index)
# #     print(type(index))
#     for j in range(len(index)):
#         index_full.append(index[j])
#     print("index_full = ", index_full)
#     print("first index = ", index_full[0])
#     gmag_near = []
#     rmag_near = []
#     color = []
#     for k in range(len(index_full)):
#         gmag_near.append(gmag_survey[index_full[k]])
#         rmag_near.append(rmag_survey[index_full[k]])
#     print("length gmag = ", len(gmag_near))
#     print("length rmag = " , len(rmag_near))
#     color.append(np.array(gmag_near) - np.array(rmag_near))
#     plt.scatter(rmag_near, color, color = "teal")
#     plt.show()
    

# gmag_near0 = []
# rmag_near0 = []

# for i in range(len(ind0)):
#     gmag_near0.append(gmag_survey[ind0[i]])
#     rmag_near0.append(rmag_survey[ind0[i]])

# # print(gmag_near0)
# # print(rmag_near0)
# print(len(ind0))
# print(len(gmag_near0))
# print(len(rmag_near0))
# print(type(rmag_near0))

# gmag_near0 = np.array(gmag_near0)
# rmag_near0 = np.array(rmag_near0)

# color = gmag_near0 - rmag_near0

# plt.scatter(rmag_near0, color, color="teal")
# plt.show()

In [ ]:
def local_bkg(distance_kpc, distance_r2, distance_r3, kpc_DA, x0, y0, x1, y1):
    
    # x0,y0 are RA/Dec at center of search radius (in this case, ra_LRG and dec_LRG)
    # x1,y1 are RA/Dec of every other source
    # distance_kpc is the distance from x0,y0 we are looking for satellites.

    from sklearn.neighbors import KDTree
    import numpy as np

    # Distance from which we are looking for satellites around the LRGs
#     distance_r2 = 2. # in Mpc
    distance_r2_kpc = distance_r2 * 10.**3. # in kpc

    dist_r2 = []
    for i in range(len(kpc_DA)):
        dist_r2.append((distance_r2_kpc / kpc_DA[i]) * 1./3600.) 

    # Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
    zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
    zip_list_BKG = list(zip(x1, y0)) # Fake EDR sources

    # Creates a tree of background sources
    gal_tree_r2 = KDTree(zip_list_BKG)

    # returns a list of background sources that are within some radius r of an LRG
    nn_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2,count_only=True)

    # find indices of near neighbors
    # creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
    # arrays could be empty
    ind_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2)

    # Distance from which we are looking for satellites around the LRGs
#     distance_r3 = 10. # in Mpc
    distance_r3_kpc = distance_r3 * 10.**3. # in kpc

    dist_r3 = []
    for i in range(len(kpc_DA)):
        dist_r3.append((distance_r3_kpc / kpc_DA[i]) * 1./3600.) 

    # Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
    zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
    zip_list_BKG = list(zip(x1, y1)) # Fake EDR sources

    # Creates a tree of EDR sources
    gal_tree_r3 = KDTree(zip_list_BKG)

    # returns a list of EDR sources that are within some radius r of an LRG
    nn_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3,count_only=True)

    # find indices of near neighbors
    # creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
    # arrays could be empty
    ind_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3)

    annulus_ind = []

    for i in range(len(ind_r3)):
        l3 = [x for x in ind_r3[i] if x not in ind_r2[i]]
        annulus_ind.append(l3)

    # print(len(new_ind[0]))

    new_ind = np.asarray(annulus_ind)

    numbkg = []
    for i in range(len(new_ind)):
        numbkg.append(len(new_ind[i]))

    med_local = np.median(numbkg)
#     print("median number of local galaxies is", med_local)


    r2 = []
    for i in range(len(kpc_DA)):
        r2.append((distance_r2_kpc / kpc_DA[i])) 
    
    r3 = []
    for i in range(len(kpc_DA)):
        r3.append((distance_r3_kpc / kpc_DA[i])) 

    area_r2 = []
    for i in range(len(dist_r2)):
        area_r2.append((np.pi * r2[i] ** 2.))
    
    area_r3 = []
    for i in range(len(dist_r3)):
        area_r3.append((np.pi * r3[i] ** 2.))
    
    area_annulus = []
    for i in range(len(dist_r3)):
        area_annulus.append(area_r3[i] - area_r2[i])
    
# print(len(area_r2))
# print(len(area_r3))
# print(len(area_annulus))


    # Creates one list of number of near neighbors for every LRG (number of lists = number of LRGs)
    # LOCAL_BKG is the list of 2D arrays of survey galaxies as a function of color and magnitude
    local_bkg = []

    for i in range(len(new_ind)):
        # Creates a zero array if there are no near neighbors
        if len(new_ind[i]) == 0:
            hist2d = np.zeros((len(xedges) - 1, len(yedges) - 1))
            local_bkg.append(hist2d)
        # Creates a 2D histogram for satellite galaxies
        else:
            hist2d, x_notuse, y_notuse = np.histogram2d(rmag_survey[new_ind[i]], color_survey[new_ind[i]], bins=(xedges, yedges), normed=False)
            local_bkg.append(hist2d)
        
    sigma = []
    for i in range(len(area_annulus)):
        sigma.append(local_bkg[i] / area_annulus[i])
                 
    omega = []
    for i in range(len(kpc_DA)):
        omega.append((np.pi * distance_kpc ** 2.) / (kpc_DA[i]) ** 2.)  # in square arcsec
                 
    Nbkg = []
    for i in range(len(omega)):
        Nbkg.append((sigma[i] * omega[i]))
                 
    Nbkg = np.asarray(Nbkg)
    
    return(numbkg, med_local, sigma, omega, Nbkg, dist_r2, dist_r3)  # returns number of galaxies in annulus, 
                                                # median number of galaxies in the annulus, the surface density sigma,
                                                # the solid angle omega, and calculated arrray of background galaxies


In [ ]:
# def local_bkg(distance_kpc, distance_r2, distance_r3, kpc_DA, x0, y0, x1, y1):
    
    # x0,y0 are RA/Dec at center of search radius (in this case, ra_LRG and dec_LRG)
    # x1,y1 are RA/Dec of every other source
    # distance_kpc is the distance from x0,y0 we are looking for satellites.

from sklearn.neighbors import KDTree
import numpy as np

# Distance from which we are looking for satellites around the LRGs
distance_r2 = 2. # in Mpc
distance_r2_kpc = distance_r2 * 10.**3. # in kpc

# Distance from which we are looking for satellites around the LRGs
distance_r3 = 5. # in Mpc
distance_r3_kpc = distance_r3 * 10.**3. # in kpc

dist_r3 = []
for i in range(len(kpc_DA)):
    dist_r3.append((distance_r3_kpc / kpc_DA[i]) * 1./3600.) 

# Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
zip_list_BKG = list(zip(x1, y1)) # Fake EDR sources

# Creates a tree of EDR sources
gal_tree_r3 = KDTree(zip_list_BKG)
    
# find indices of sources
# creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
# arrays could be empty
ind_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3)

# returns a list of EDR sources that are within some radius r of an LRG
nn_r3, d_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3,return_distance=True)

# print(d_r3.shape)
# print(d_r3[0])
# print(d_r3[1])
# print(d_r3[2])
# print(len(d_r3))

d_r3_arcsec = d_r3 * 3600.
# print(d_r3_arcsec[1])
d_r3_kpc = d_r3 * 3600. * kpc_DA
# print(d_r3_kpc[1])
# print(d_r3_kpc.shape)
d_r3_Mpc = d_r3_kpc * (1./1000.)
# print(d_r3_Mpc[1])



dist_outer_arcsec = []
dist_outer_kpc = []
dist_outer_Mpc = []
for i in range(len(kpc_DA)):
    dist_outer_arcsec.append(d_r3[i] * 3600.)
    # print(d_r3_arcsec)
    dist_outer_kpc.append(d_r3[i] * 3600. * kpc_DA[i])
    # print(d_r3_kpc)
    dist_outer_Mpc.append(dist_outer_kpc[i] * (1. / 1000.))
    # print(d_r3_Mpc)
    

d1 = np.asarray(dist_outer_arcsec)
d2 = np.asarray(dist_outer_kpc)
d3 = np.asarray(dist_outer_Mpc)

print('--------------------')
print(d1[10])
print(d_r3_arcsec[10])
print(d2[10])
print(d_r3_kpc[10])
print(d3[10])
print(d_r3_Mpc[10])
print('--------------------')

print('--------------------')
print(d_r3[10])
print(kpc_DA[10])
print('--------------------')

# print(d1.shape)
# print(d2.shape)
# print(d3.shape)
    
# print(d_r3_Mpc[2])
# print(len(d_r3_Mpc[2][np.where(d_r3_Mpc[2] > 2.)]))
# print(len(d_r3_Mpc[2]))

source_num1 = []
source_num2 = []
source_num3 = []
source_num4 = []
source_num5 = []
source_num6 = []

for i in range(len(d_r3_Mpc)):
    source_num1.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 2.) & (d_r3_Mpc[i] < 2.5))]))
    source_num2.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 2.5) & (d_r3_Mpc[i] < 3.))]))
    source_num3.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 3.) & (d_r3_Mpc[i] < 3.5))]))
    source_num4.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 3.5) & (d_r3_Mpc[i] < 4.))]))
    source_num5.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 4.) & (d_r3_Mpc[i] < 4.5))]))
    source_num6.append(len(d_r3_Mpc[i][np.where((d_r3_Mpc[i] >= 4.5) & (d_r3_Mpc[i] <= 5.))]))


# print(np.sum(source_num1))
# area of annulus = pi * (outer radius**2 - inner radius**2)
# print(ind_r3[2])
# print(len(nn_r3[0]))
# print(len(nn_r3[1]))
# print(d_r3_Mpc[2])

# print(ind_r3[2][np.where((d_r3_Mpc[2] >= 3.) & (d_r3_Mpc[2] < 3.5))])

bkg1 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 2.) & (d_r3_Mpc[i] < 2.5))]) == 0:
        temp1 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg1.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp1, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 2.) & (d_r3_Mpc[i] < 2.5))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 2.) & (d_r3_Mpc[i] < 2.5))]], bins=(xedges, yedges), normed=False)
        bkg1.append(temp1)

# print(np.sum(bkg1))
# print(np.sum(source_num1))

bkg2 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 2.5) & (d_r3_Mpc[i] < 3.))]) == 0:
        temp2 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg2.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp2, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 2.5) & (d_r3_Mpc[i] < 3.))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 2.5) & (d_r3_Mpc[i] < 3.))]], bins=(xedges, yedges), normed=False)
        bkg2.append(temp2)
        
# print(np.sum(bkg2))
# print(np.sum(source_num2))
        
bkg3 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 3.) & (d_r3_Mpc[i] < 3.5))]) == 0:
        temp3 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg3.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp3, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 3.) & (d_r3_Mpc[i] < 3.5))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 3.) & (d_r3_Mpc[i] < 3.5))]], bins=(xedges, yedges), normed=False)
        bkg3.append(temp3)

# print(np.sum(bkg3))
# print(np.sum(source_num3))
    
bkg4 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 3.5) & (d_r3_Mpc[i] < 4.))]) == 0:
        temp4 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg4.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp4, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 3.5) & (d_r3_Mpc[i] < 4))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 3.5) & (d_r3_Mpc[i] < 4.))]], bins=(xedges, yedges), normed=False)
        bkg4.append(temp4)


# print(np.sum(bkg4))
# print(np.sum(source_num4))        
        
bkg5 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 4.) & (d_r3_Mpc[i] < 4.5))]) == 0:
        temp5 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg5.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp5, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 4.) & (d_r3_Mpc[i] < 4.5))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 4.) & (d_r3_Mpc[i] < 4.5))]], bins=(xedges, yedges), normed=False)
        bkg5.append(temp5)

# print(np.sum(bkg5))
# print(np.sum(source_num5))        
        
bkg6 = []
for i in range(len(ind_r3)):
    # Creates a zero array if there are no near neighbors
    if len(ind_r3[i][np.where((d_r3_Mpc[i] >= 4.5) & (d_r3_Mpc[i] <= 5.))]) == 0:
        temp6 = np.zeros((len(xedges) - 1, len(yedges) - 1))
        bkg6.append(temp1)
    # Creates a 2D histogram for satellite galaxies
    else:
        temp6, x_notuse, y_notuse = np.histogram2d(rmag_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 4.5) & (d_r3_Mpc[i] <= 5.))]], color_survey[ind_r3[i][np.where((d_r3_Mpc[i] >= 4.5) & (d_r3_Mpc[i] <= 5.))]], bins=(xedges, yedges), normed=False)
        bkg6.append(temp6)
 
# print(np.sum(bkg6))
# print(np.sum(source_num6))


# Area of an annulus A = pi * (outer radius**2 - inner radius**2)

r1 = 2.
r2 = 2.5
r3 = 3.
r4 = 3.5
r5 = 4.
r6 = 4.5
r7 = 5.

A1 = np.pi * (r2**2 - r1**2)
A2 = np.pi * (r3**2 - r2**2)
A3 = np.pi * (r4**2 - r3**2)
A4 = np.pi * (r5**2 - r4**2)
A5 = np.pi * (r6**2 - r5**2)
A6 = np.pi * (r7**2 - r6**2)

sigma1 = []
for i in range(len(bkg1)):
    sigma1.append(bkg1[i]/A1)    

sigma2 = []
for i in range(len(bkg2)):
    sigma2.append(bkg2[i]/A2)
    
sigma3 = []
for i in range(len(bkg3)):
    sigma3.append(bkg3[i]/A3)
    
sigma4 = []
for i in range(len(bkg4)):
    sigma4.append(bkg4[i]/A4)
    
sigma5 = []
for i in range(len(bkg5)):
    sigma5.append(bkg5[i]/A5)

sigma6 = []
for i in range(len(bkg6)):
    sigma6.append(bkg6[i]/A6)

sum_sigma1 = np.sum(sigma1)
# print(sum_sigma1)
sum_sigma2 = np.sum(sigma2)
# print(sum_sigma2)
sum_sigma3 = np.sum(sigma3)
# print(sum_sigma3)
sum_sigma4 = np.sum(sigma4)
# print(sum_sigma4)
sum_sigma5 = np.sum(sigma5)
# print(sum_sigma5)
sum_sigma6 = np.sum(sigma6)
# print(sum_sigma6)

error1 = np.sqrt(sum_sigma1)/sum_sigma1
error2 = np.sqrt(sum_sigma2)/sum_sigma2
error3 = np.sqrt(sum_sigma3)/sum_sigma3
error4 = np.sqrt(sum_sigma4)/sum_sigma4
error5 = np.sqrt(sum_sigma5)/sum_sigma5
error6 = np.sqrt(sum_sigma6)/sum_sigma6

error = [error1, error2, error3, error4, error5, error6]

sum_sigma = [sum_sigma1, sum_sigma2, sum_sigma3, sum_sigma4, sum_sigma5, sum_sigma6]
radius = [2.5, 3., 3.5, 4., 4.5, 5.]

plt.scatter(radius, sum_sigma)
plt.errorbar(radius, sum_sigma, yerr = error, ecolor='red')
plt.show()

In [ ]:
local_gal1, med1, sigma1, omega1, Nbkg1, dist_r2, dist_r3 = local_bkg(distance_kpc, 5, 10, kpc_DA, x0, y0, x1, y1)

plt.scatter(x1, y1, s = 3, color='red')
plt.scatter(x0, y0, s = 3, color='blue')

# Draws circle of some radius around the LRG sources
# Circles too small to really see in the plot, but I have tested it with bigger radii to make sure it works if I
# ever need it.
circle = []
for i in range(len(x0)):
    circle1 = plt.Circle((x0[i],y0[i]), dist[i], color='pink', fill=False)
    circle2 = plt.Circle((x0[i],y0[i]), dist_r2[i], color='green', fill=False)
    circle3 = plt.Circle((x0[i],y0[i]), dist_r3[i], color='purple', fill=False)
    plt.gcf().gca().add_artist(circle1)
    plt.gcf().gca().add_artist(circle2)
    plt.gcf().gca().add_artist(circle3)
plt.show()

# local_gal2, med2, sigma2, omega2, Nbkg2 = local_bkg(distance_kpc, 5, 15, kpc_DA, x0, y0, x1, y1)
# local_gal3, med3, sigma3, omega3, Nbkg3 = local_bkg(distance_kpc, 5, 20, kpc_DA, x0, y0, x1, y1)
# local_gal4, med4, sigma4, omega4, Nbkg4 = local_bkg(distance_kpc, 5, 25, kpc_DA, x0, y0, x1, y1)
# local_gal5, med5, sigma5, omega5, Nbkg5 = local_bkg(distance_kpc, 5, 30, kpc_DA, x0, y0, x1, y1)
# local_gal6, med6, sigma6, omega6, Nbkg6 = local_bkg(distance_kpc, 5, 35, kpc_DA, x0, y0, x1, y1)
# local_gal7, med7, sigma7, omega7, Nbkg7 = local_bkg(distance_kpc, 5, 40, kpc_DA, x0, y0, x1, y1)
# local_gal8, med8, sigma8, omega8, Nbkg8 = local_bkg(distance_kpc, 5, 45, kpc_DA, x0, y0, x1, y1)
# local_gal9, med9, sigma9, omega9, Nbkg9 = local_bkg(distance_kpc, 5, 50, kpc_DA, x0, y0, x1, y1)

print(med1)
# print(med2)
# print(med3)
# print(med4)
# print(med5)
# print(med6)
# print(med7)
# print(med8)
# print(med9)
print('-----------')

Nsat1 = np.array(near) - np.array(Nbkg1)
# Nsat2 = np.array(near) - np.array(Nbkg2)
# Nsat3 = np.array(near) - np.array(Nbkg3)
# Nsat4 = np.array(near) - np.array(Nbkg4)
# Nsat5 = np.array(near) - np.array(Nbkg5)
# Nsat6 = np.array(near) - np.array(Nbkg6)
# Nsat7 = np.array(near) - np.array(Nbkg7)
# Nsat8 = np.array(near) - np.array(Nbkg8)
# Nsat9 = np.array(near) - np.array(Nbkg9)

sumsat1 = []
# Sum up number of satellite galaxies for every LRG
for i in range(len(Nsat1)):
    sumsat1.append(np.sum(Nsat1[i]))
    
# sumsat2 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat3)):
#     sumsat2.append(np.sum(Nsat2[i]))
    
# sumsat3 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat3)):
#     sumsat3.append(np.sum(Nsat3[i]))
    
# sumsat4 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat4)):
#     sumsat4.append(np.sum(Nsat4[i]))
    
# sumsat5 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat5)):
#     sumsat5.append(np.sum(Nsat5[i]))
    
# sumsat6 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat6)):
#     sumsat6.append(np.sum(Nsat6[i]))
    
# sumsat7 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat7)):
#     sumsat7.append(np.sum(Nsat7[i]))
    
# sumsat8 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat8)):
#     sumsat8.append(np.sum(Nsat8[i]))
    
# sumsat9 = []
# # Sum up number of satellite galaxies for every LRG
# for i in range(len(Nsat9)):
#     sumsat9.append(np.sum(Nsat9[i]))
    
print(np.median(sumsat1))
# print(np.median(sumsat2))
# print(np.median(sumsat3))
# print(np.median(sumsat4))
# print(np.median(sumsat5))
# print(np.median(sumsat6))
# print(np.median(sumsat7))
# print(np.median(sumsat8))
# print(np.median(sumsat9))

# medians_sat = [np.median(sumsat1), np.median(sumsat2), np.median(sumsat3), np.median(sumsat4), np.median(sumsat5), np.median(sumsat6), np.median(sumsat7), np.median(sumsat8), np.median(sumsat9)]

# medians_num = [med1, med2, med3, med4, med5, med6, med7, med8, med9]

# plt.scatter(medians_sat, medians_num)
# plt.show()


In [ ]:
# Calculate NUMBER OF EXPECTED INTERLOPER GALAXIES (Nbkg)

# Distance from which we are looking for satellites around the LRGs
distance_r2 = 2. # in Mpc
distance_r2_kpc = distance_r2 * 10.**3. # in kpc

dist_r2 = []
for i in range(len(kpc_DA)):
    dist_r2.append((distance_r2_kpc / kpc_DA[i]) * 1./3600.) 

# Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
zip_list_BKG = list(zip(x1, y0)) # Fake EDR sources
# print(zip_list_lrg)
# print(type(zip_list_BKG))
# print(zip_list_LRG[0])
# print(type(zip_list_LRG[0]))
# print(type(zip_list_BKG[0]))
# print('len zip_list_LRG', len(zip_list_LRG))

# Creates a tree of EDR sources
gal_tree_r2 = KDTree(zip_list_BKG)

# returns a list of EDR sources that are within some radius r of an LRG
nn_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2,count_only=True)

# find indices of near neighbors
# creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
# arrays could be empty
ind_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2)
# print(ind)
# print(type(ind[5]))
# ind5_r2 = ind_r2[0]
# print(ind5_r2)
# print(len(ind5_r2))


# Distance from which we are looking for satellites around the LRGs
distance_r3 = 10. # in Mpc
distance_r3_kpc = distance_r3 * 10.**3. # in kpc

dist_r3 = []
for i in range(len(kpc_DA)):
    dist_r3.append((distance_r3_kpc / kpc_DA[i]) * 1./3600.) 

# Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
zip_list_BKG = list(zip(x1, y1)) # Fake EDR sources
# print(zip_list_lrg)
# print(type(zip_list_BKG))
# print(zip_list_LRG[0])
# print(type(zip_list_LRG[0]))
# print(type(zip_list_BKG[0]))
# print('len zip_list_LRG', len(zip_list_LRG))

# Creates a tree of EDR sources
gal_tree_r3 = KDTree(zip_list_BKG)

# returns a list of EDR sources that are within some radius r of an LRG
nn_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3,count_only=True)

# find indices of near neighbors
# creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
# arrays could be empty
ind_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3)
# print(ind)
# print(type(ind[5]))
# ind5_r3 = ind_r3[0]
# print(ind5_r3)
# print(len(ind5_r3))

diff = len(ind_r3[0]) - len(ind_r2[0])
# print(diff)

# print(len(ind_r3))

# l3 = [x for x in ind5_r3 if x not in ind5_r2]
# print(len(l3))


def CommonInd(list1, list2):
    annulus_ind = []

    for i in range(len(list1)):
        l3 = [x for x in list1[i] if x not in list2[i]]
        annulus_ind.append(l3)
        
    return(annulus_ind)

new_ind = CommonInd(ind_r3, ind_r2)
# print(len(new_ind))

# print(len(new_ind[0]))

new_ind = np.asarray(new_ind)

# Plots LRG sources and EDR sources
# plt.scatter(x1, y1, s = 3, color='red')
# plt.scatter(x0, y0, s = 3, color='blue')

# Draws circle of some radius around the LRG sources
# Circles too small to really see in the plot, but I have tested it with bigger radii to make sure it works if I
# ever need it.
# circle = []
# for i in range(len(x0)):
#     circle1 = plt.Circle((x0[i],y0[i]), dist[i], color='green', fill=False)
#     circle2 = plt.Circle((x0[i],y0[i]), dist_r2[i], color='black', fill=False)
#     circle3 = plt.Circle((x0[i],y0[i]), dist_r3[i], color='purple', fill=False)
#     plt.gcf().gca().add_artist(circle1)
#     plt.gcf().gca().add_artist(circle2)
#     plt.gcf().gca().add_artist(circle3)

# circle1 = plt.Circle((x0[49], y0[49]), dist[49], color='green', fill=False)
# circle2 = plt.Circle((x0[49], y0[49]), dist_r2[49], color='pink', fill=False)
# circle3 = plt.Circle((x0[49], y0[49]), dist_r3[49], color='purple', fill=False)
# plt.gcf().gca().add_artist(circle1)
# plt.gcf().gca().add_artist(circle2)
# plt.gcf().gca().add_artist(circle3)

# plt.show()

# print(len(new_ind[49]))

new_ind = np.asarray(new_ind)

numbkg = []
for i in range(len(new_ind)):
    numbkg.append(len(new_ind[i]))

med_local = np.median(numbkg)
print("median number of local galaxies is", med_local)

# print(len(numbkg))
# print(len(new_ind))
# print(new_ind.shape)
print(new_ind[0])
print(len(new_ind[1]))

print(nn_r3)
# print(len(nn_r3))
print(numbkg)

In [ ]:
# print(new_ind.shape)

# print(len(dist_r2))
# print(len(dist_r3))

r2 = []
for i in range(len(kpc_DA)):
    r2.append((distance_r2_kpc / kpc_DA[i])) 
    
r3 = []
for i in range(len(kpc_DA)):
    r3.append((distance_r3_kpc / kpc_DA[i])) 

area_r2 = []
for i in range(len(dist_r2)):
    area_r2.append((np.pi * r2[i] ** 2.))
    
area_r3 = []
for i in range(len(dist_r3)):
    area_r3.append((np.pi * r3[i] ** 2.))
    
area_annulus = []
for i in range(len(dist_r3)):
    area_annulus.append(area_r3[i] - area_r2[i])
    
print(len(area_r2))
print(len(area_r3))
print(len(area_annulus))


# Creates one list of number of near neighbors for every LRG (number of lists = number of LRGs)
# LOCAL_BKG is the list of 2D arrays of survey galaxies as a function of color and magnitude
local_bkg = []

for i in range(len(new_ind)):
    # Creates a zero array if there are no near neighbors
    if len(new_ind[i]) == 0:
        hist2d = np.zeros((len(xedges) - 1, len(yedges) - 1))
        local_bkg.append(hist2d)
    # Creates a 2D histogram for satellite galaxies
    else:
        hist2d, x_notuse, y_notuse = np.histogram2d(rmag_survey[new_ind[i]], color_survey[new_ind[i]], bins=(xedges, yedges), normed=False)
        local_bkg.append(hist2d)
        
sigma = []
for i in range(len(area_annulus)):
    sigma.append(local_bkg[i] / area_annulus[i])
                 
omega = []
for i in range(len(kpc_DA)):
    omega.append((np.pi * distance_kpc ** 2.) / (kpc_DA[i]) ** 2.)  # in square arcsec
                 
Nbkg = []
for i in range(len(omega)):
    Nbkg.append((sigma[i] * omega[i]))
                 
Nbkg = np.asarray(Nbkg)
print(Nbkg.shape)

# print(Nbkg)
# print(area_annulus)


In [ ]:
# Calculates number of expected interloper galaxies by first calculating the solid angle omega enclosed in radius r from 
# the LRG. Then find the number of interloper galaxies by multiplying omega by the surface density to find the 
# number of interloper galaxies as a function of color and magnitude.

# area = []
# area = np.pi * distance**2. # in square Mpc
# print("comoving radial distance = ",DCMR_Mpc)

# Calculate solid angle omega for every rad
omega = []

for i in range(len(kpc_DA)):
    omega.append((np.pi * distance_kpc**2.)/(kpc_DA[i])**2.) # in square arcsec

# print("rad is", rad)
print("omega is", omega)
# print(type(omega))
# print(r[1]) 


# Multiply omega by the surface density
# Like the code above, this needs to be reshaped to make bins of color and magnitude.
Nbkg = []

for i in range(len(omega)):
    bkg = sd * omega[i]
    Nbkg.append(bkg)
#     print(i)
#     print(Nbkg[i])
    
print(np.shape(Nbkg))
print("Nbkg is", Nbkg[0])
    
# Plots LRG sources and EDR sources
plt.scatter(x1, y1, s = 1, color='red')
plt.scatter(x0, y0, s = 1, color='blue')

circle = []
for i in range(len(x0)):
    circle = plt.Circle((x0[i],y0[i]), dist[i], color='green', fill=False)
    plt.gcf().gca().add_artist(circle)
    
a = np.arange(0,50)
for i, txt in enumerate(a):
    text = plt.annotate(txt, (x0[i],y0[i]))
    text.set_fontsize(7)
    
# plt.xlim(0.,1.)
# plt.ylim(1.,2.)
plt.show()

In [ ]:
print(sd)
print("")
print(omega)
print("")
print(sd[0])
print(sd[0]*omega[0])


In [ ]:
# Calculate number of satellite galaxies by subtracting interloper galaxies from near neighbor galaxies as a function 
# of color and magnitude.

Nsat = np.array(near) - np.array(Nbkg)

# print(len(Nsat))
# print(np.shape(Nsat))
# print(Nsat[0])
# print(type(Nsat))
# Nsat = np.array(Nsat)
# print(type(Nsat))

# print("Nsat0")
# plt.imshow(Nsat[0], cmap=plt.cm.PuRd, extent=(xedges[0], xedges[len(xedges)-1], yedges[0], yedges[len(yedges)-1]))
# plt.colorbar(orientation='vertical')
# plt.gca().invert_xaxis()
# # plt.title("Surface Density Histogram")
# plt.show()
# print("")

# print("Nsat1")
# plt.imshow(Nsat[1], cmap=plt.cm.PuRd, extent=(xedges[0], xedges[len(xedges)-1], yedges[0], yedges[len(yedges)-1]))
# plt.colorbar(orientation='vertical')
# plt.gca().invert_xaxis()
# # plt.title("Surface Density Histogram")
# plt.show()
# print("")

# print("Nsat2")
# plt.imshow(Nsat[2], cmap=plt.cm.PuRd, extent=(xedges[0], xedges[len(xedges)-1], yedges[0], yedges[len(yedges)-1]))
# plt.colorbar(orientation='vertical')
# plt.gca().invert_xaxis()
# # plt.title("Surface Density Histogram")
# plt.show()
# print("")

In [ ]:
# In which I try to make a table of this data so I can actually analyze it

# import pandas as pd
# from tabulate import tabulate

# # x = [1,2,3,4]
# # y = ['one', 'two', 'three', 'four']

# # d = {'x': x, 'y': y}

# sumsat = []
# sumbkg = []
# sumnear = []

# for i in range(len(Nsat)):
#     sumsat.append(np.sum(Nsat[i]))

# for i in range(len(Nbkg)):
#     sumbkg.append(np.sum(Nbkg[i]))
    
# for i in range(len(near)):
#     sumnear.append(np.sum(near[i]))


# d = {'projected radius': dist, 'LRG redshift': z_lrg, 'number of near neighbors': num, 'number of interlopers': sumbkg, 'number of satellites': sumsat}

# # fig, ax = plt.subplots()
# # fig.patch.set_visible(False)
# # ax.axis('off')
# # ax.axis('tight')

# df = pd.DataFrame(data=d)

# print(tabulate(df, headers='keys', tablefmt='latex'))

# # ax.table(cellText=df.values, colLabels=df.columns, loc='center')
# # fig.tight_layout()
# # plt.show()

# meannear = np.mean(sumnear)
# print("nearmean is", meannear)

# sdnear = np.std(sumnear)
# print("sdnear", sdnear)

# meanbkg = np.mean(sumbkg)
# print("meankbg is", meanbkg)

# sdbkg = np.std(sumbkg)
# print("sdbkg is", sdbkg)

# meansat = np.mean(sumsat)
# print("meansat is", meansat)

# sdsat = np.std(sumsat)
# print("sdsat is", sdsat)

# plt.hist(sumsat, bins=50)
# plt.show()

In [ ]:
sumsat = []
sumbkg = []
sumnear = []

# Sum up number of satellite galaxies for every LRG
for i in range(len(Nsat)):
    sumsat.append(np.sum(Nsat[i]))

# Sum up number of background galaxies for every LRG
for i in range(len(Nbkg)):
    sumbkg.append(np.sum(Nbkg[i]))
    
# Sum up number of near neighbors for every LRG
for i in range(len(near)):
    sumnear.append(np.sum(near[i]))

meannear = np.mean(sumnear)
print("mean near neighbor is", meannear)

sdnear = np.std(sumnear)
print("standard deviation of near neighbor is", sdnear)

meanbkg = np.mean(sumbkg)
print("mean interloper is", meanbkg)

sdbkg = np.std(sumbkg)
print("standard deviation of interloper is", sdbkg)

meansat = np.mean(sumsat)
print("mean number of satellites is", meansat)

medsat = np.median(sumsat)
print("median number of satellites is", medsat)

sdsat = np.std(sumsat)
print("standard deviation of satellites is", sdsat)

plt.title("Histogram of the Number of Satellite Galaxies")
plt.hist(sumsat, bins=25)
plt.axvline(linewidth=1, color='r')
plt.show()

plt.title("Histogram of the Number of Near Neighbors")
plt.hist(sumnear, bins=25)
plt.show()

plt.title("Histogram of the Number of Expected Interlopers")
plt.hist(sumbkg, bins=25)
plt.show()


In [ ]:
def boot_med_plot(niter, confint, boot_func, array):

    from astropy.stats import bootstrap
    from astropy.utils import NumpyRNGContext

# niter = 1000
    with NumpyRNGContext(1):
        bootmed = bootstrap(np.asarray(array), bootnum=niter, bootfunc=boot_func)
#         bootmean = bootstrap(np.asarray(sumsat), bootnum=niter, bootfunc=np.mean)
    

# Compute confidence interval of median

#     confint = 0.68
    sortmed = sorted(bootmed)
    lowind = int(round((1 - confint)/2*niter, 2))
    highind = int(round((1-((1 - confint)/2))*niter, 2))
    
    plt.title("Histogram of Nsat Bootstrapped Median")
    plt.hist(bootmed, bins=25, color='purple', alpha=0.5)
# plt.hist(bootmean, bins=25, color='violet', alpha=0.5)
    plt.axvline(x=sortmed[lowind])
    plt.axvline(x=sortmed[highind])
    plt.xlabel(r'$bootstrap$')
    plt.ylabel(r'$counts$')
    plt.show()

    print("The median of Nsat:", np.median(array))
    print("The median of bootmed:", np.median(bootmed))
    print("The standard deviation of bootmed:", np.std(bootmed))
#     print("The mean of Nsat:", np.mean(sumsat))
    print("Low 68% confidence interval:", sortmed[lowind])
    print("High 68% confidence interval:", sortmed[highind])
    
    

boot_med_plot(1000, 0.68, np.median, sumsat)

In [ ]:
# input values: distance, distance_r2, distance_r3, kpc_DA, x0, y0, x1, y1
# output values: Nbkg, local_med

# Calculate NUMBER OF EXPECTED INTERLOPER GALAXIES (Nbkg)

distance_r3 = 10. # in Mpc
distance_r2 = 2. # in Mpc

def local_bkg(distance_kpc, distance_r2, distance_r3, kpc_DA, x0, y0, x1, y1):
    
    # x0,y0 are RA/Dec at center of search radius (in this case, ra_LRG and dec_LRG)
    # x1,y1 are RA/Dec of every other source
    # distance_kpc is the distance from x0,y0 we are looking for satellites.

    from sklearn.neighbors import KDTree
    import numpy as np

    # Distance from which we are looking for satellites around the LRGs
#     distance_r2 = 2. # in Mpc
    distance_r2_kpc = distance_r2 * 10.**3. # in kpc

    dist_r2 = []
    for i in range(len(kpc_DA)):
        dist_r2.append((distance_r2_kpc / kpc_DA[i]) * 1./3600.) 

    # Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
    zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
    zip_list_BKG = list(zip(x1, y0)) # Fake EDR sources

    # Creates a tree of background sources
    gal_tree_r2 = KDTree(zip_list_BKG)

    # returns a list of background sources that are within some radius r of an LRG
    nn_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2,count_only=True)

    # find indices of near neighbors
    # creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
    # arrays could be empty
    ind_r2 = gal_tree_r2.query_radius(zip_list_LRG,r=dist_r2)

    # Distance from which we are looking for satellites around the LRGs
#     distance_r3 = 10. # in Mpc
    distance_r3_kpc = distance_r3 * 10.**3. # in kpc

    dist_r3 = []
    for i in range(len(kpc_DA)):
        dist_r3.append((distance_r3_kpc / kpc_DA[i]) * 1./3600.) 

    # Creates a list of ordered pairs; zips ra and dec together so they can be fed into KDTree
    zip_list_LRG = list(zip(x0, y0)) # Fake LRG sources
    zip_list_BKG = list(zip(x1, y1)) # Fake EDR sources

    # Creates a tree of EDR sources
    gal_tree_r3 = KDTree(zip_list_BKG)

    # returns a list of EDR sources that are within some radius r of an LRG
    nn_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3,count_only=True)

    # find indices of near neighbors
    # creates a list of arrays that include the indices of satellite galaxies per LRG. In general, some or all of these
    # arrays could be empty
    ind_r3 = gal_tree_r3.query_radius(zip_list_LRG,r=dist_r3)

    annulus_ind = []

    for i in range(len(ind_r3)):
        l3 = [x for x in ind_r3[i] if x not in ind_r2[i]]
        annulus_ind.append(l3)

    # print(len(new_ind[0]))

    new_ind = np.asarray(annulus_ind)

    numbkg = []
    for i in range(len(new_ind)):
        numbkg.append(len(new_ind[i]))

    med_local = np.median(numbkg)
#     print("median number of local galaxies is", med_local)


    r2 = []
    for i in range(len(kpc_DA)):
        r2.append((distance_r2_kpc / kpc_DA[i])) 
    
    r3 = []
    for i in range(len(kpc_DA)):
        r3.append((distance_r3_kpc / kpc_DA[i])) 

    area_r2 = []
    for i in range(len(dist_r2)):
        area_r2.append((np.pi * r2[i] ** 2.))
    
    area_r3 = []
    for i in range(len(dist_r3)):
        area_r3.append((np.pi * r3[i] ** 2.))
    
    area_annulus = []
    for i in range(len(dist_r3)):
        area_annulus.append(area_r3[i] - area_r2[i])
    
# print(len(area_r2))
# print(len(area_r3))
# print(len(area_annulus))


    # Creates one list of number of near neighbors for every LRG (number of lists = number of LRGs)
    # LOCAL_BKG is the list of 2D arrays of survey galaxies as a function of color and magnitude
    local_bkg = []

    for i in range(len(new_ind)):
        # Creates a zero array if there are no near neighbors
        if len(new_ind[i]) == 0:
            hist2d = np.zeros((len(xedges) - 1, len(yedges) - 1))
            local_bkg.append(hist2d)
        # Creates a 2D histogram for satellite galaxies
        else:
            hist2d, x_notuse, y_notuse = np.histogram2d(rmag_survey[new_ind[i]], color_survey[new_ind[i]], bins=(xedges, yedges), normed=False)
            local_bkg.append(hist2d)
        
    sigma = []
    for i in range(len(area_annulus)):
        sigma.append(local_bkg[i] / area_annulus[i])
                 
    omega = []
    for i in range(len(kpc_DA)):
        omega.append((np.pi * distance_kpc ** 2.) / (kpc_DA[i]) ** 2.)  # in square arcsec
                 
    Nbkg = []
    for i in range(len(omega)):
        Nbkg.append((sigma[i] * omega[i]))
                 
    Nbkg = np.asarray(Nbkg)
    
    return(local_med, Nbkg)
